//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESSerialNumberAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MMS_MAT
    {
        public string MMS_MAT_SID { get; set; }
        public string MATERIALNO { get; set; }
        public string MATERIALNAME { get; set; }
        public string SPEC { get; set; }
        public string MMS_TYPE_SID { get; set; }
        public string TYPE { get; set; }
        public string UNIT { get; set; }
        public string SUNIT { get; set; }
        public Nullable<decimal> SAFEQTY { get; set; }
        public Nullable<decimal> ENDQTY { get; set; }
        public string CONSUMEFLAG { get; set; }
        public string COMPMANAGE { get; set; }
        public string QTYCONSUMETYPE { get; set; }
        public string UPLOADTYPE { get; set; }
        public Nullable<decimal> WTIME { get; set; }
        public Nullable<decimal> QTIME { get; set; }
        public string STATUS { get; set; }
        public string ACTIVEFLAG { get; set; }
        public Nullable<double> TAG { get; set; }
        public string USERID { get; set; }
        public string UPDATETIME { get; set; }
        public string CATEGORY { get; set; }
        public string USETYPE { get; set; }
        public string VALIDTYPE { get; set; }
        public string ISHAVEKEYPART { get; set; }
        public string CREATEMLOTTYPE { get; set; }
        public string RECEIVEBYWOFLAG { get; set; }
        public string ISSUEGROUP { get; set; }
        public string USERDEFINECOL01 { get; set; }
        public string USERDEFINECOL02 { get; set; }
        public string USERDEFINECOL03 { get; set; }
        public string USERDEFINECOL04 { get; set; }
        public string USERDEFINECOL05 { get; set; }
        public string USERDEFINECOL06 { get; set; }
        public string USERDEFINECOL07 { get; set; }
        public string USERDEFINECOL08 { get; set; }
        public string USERDEFINECOL09 { get; set; }
        public string USERDEFINECOL10 { get; set; }
        public string USERDEFINECOL11 { get; set; }
        public string USERDEFINECOL12 { get; set; }
        public string USERDEFINECOL13 { get; set; }
        public string USERDEFINECOL14 { get; set; }
        public string USERDEFINECOL15 { get; set; }
        public string USERDEFINECOL16 { get; set; }
        public string USERDEFINECOL17 { get; set; }
        public string USERDEFINECOL18 { get; set; }
        public string USERDEFINECOL19 { get; set; }
        public string USERDEFINECOL20 { get; set; }
        public string USERDEFINECOL21 { get; set; }
        public string USERDEFINECOL22 { get; set; }
        public string USERDEFINECOL23 { get; set; }
        public string USERDEFINECOL24 { get; set; }
        public string USERDEFINECOL25 { get; set; }
        public string USERDEFINECOL26 { get; set; }
        public string USERDEFINECOL27 { get; set; }
        public string USERDEFINECOL28 { get; set; }
        public string USERDEFINECOL29 { get; set; }
        public string USERDEFINECOL30 { get; set; }
    }
}
