//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESSerialNumberAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MESSNDBEntities : DbContext
    {
        public MESSNDBEntities()
            : base("name=MESSNDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodeMast> CodeMast { get; set; }
        public virtual DbSet<PartCoding> PartCoding { get; set; }
        public virtual DbSet<PartMast> PartMast { get; set; }
        public virtual DbSet<SctlMast> SctlMast { get; set; }
        public virtual DbSet<SerialData> SerialData { get; set; }
        public virtual DbSet<SerialHist> SerialHist { get; set; }
        public virtual DbSet<vPartCoding> vPartCoding { get; set; }
        public virtual DbSet<vPartMast> vPartMast { get; set; }
        public virtual DbSet<vSerialData> vSerialData { get; set; }
    }
}
