//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MesSerialNumber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IF_WO_BOM
    {
        public string SID { get; set; }
        public string AUFNR { get; set; }
        public string POSNR { get; set; }
        public string MATNR { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string VORNR { get; set; }
        public string ALPGR { get; set; }
        public string ALPST { get; set; }
        public Nullable<decimal> ALPRF { get; set; }
        public Nullable<decimal> EWAHR { get; set; }
        public string BWART { get; set; }
        public string RSNUM { get; set; }
        public string RSPOS { get; set; }
        public string XLOEK { get; set; }
        public string RGEKS { get; set; }
        public string DUMPS { get; set; }
        public string SCHGT { get; set; }
        public string MEINS { get; set; }
    }
}
